import 'bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import './libs/jquery.barrating.min';
import './libs/jquery-scrolltofixed-min';
import './header';
import './leftBar';
import './test';
import './addBulletin';
import './bulletin-details';
